#!/bin/bash
# NeuroSwarm Fresh Run Script
# Backs up current data, resets state, recompiles, and starts a clean run.
#
# Usage: ./scripts/fresh_run.sh [--no-build]

set -euo pipefail
cd "$(dirname "$0")/.."

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="data/backup_pre_reset_${TIMESTAMP}"

echo "════════════════════════════════════════════════"
echo "  NeuroSwarm Fresh Run — $(date)"
echo "════════════════════════════════════════════════"

# ── 1. Kill any running instance ──
echo ""
echo "[1/5] Stopping running instances..."
pkill -f 'cerebral_matrix' 2>/dev/null && echo "  Killed cerebral_matrix" || echo "  No cerebral_matrix running"
sleep 1
# Kill any orphaned lobes
for lobe in thalamus primordial_loop frontal_executive basal_ganglia motor_lobe \
            synaptic_controller hippocampus homeostasis amygdala metacognition \
            critic_lobe visual_lobe wernicke_lobe rem_engine chronos_lobe \
            statistics_lobe concept_lobe causal_lobe visualizer; do
    pkill -f "build/${lobe}" 2>/dev/null && echo "  Killed ${lobe}" || true
done
# Kill spike workers
pkill -f 'spike_worker' 2>/dev/null && echo "  Killed spike workers" || true
sleep 1

# ── 2. Backup current state ──
echo ""
echo "[2/5] Backing up current state to ${BACKUP_DIR}..."
mkdir -p "${BACKUP_DIR}/metrics"

# State files (small, always backup)
for f in self_model.json self_model_primordial.json world_state.json \
         command_genome.json knowledge_gaps.json causal_graph.json \
         concept_hierarchy.json concept_clusters.json meta_templates.json \
         operators.jsonl concept_space.jsonl; do
    [ -f "data/${f}" ] && cp "data/${f}" "${BACKUP_DIR}/${f}" && echo "  ✓ ${f}"
done

# Metrics (important for eval comparison)
for f in data/metrics/*.jsonl; do
    [ -f "$f" ] && cp "$f" "${BACKUP_DIR}/metrics/" && echo "  ✓ metrics/$(basename $f)"
done

# Specialist caches
for f in data/specialist_*.json; do
    [ -f "$f" ] && cp "$f" "${BACKUP_DIR}/" && echo "  ✓ $(basename $f)"
done

echo "  Backup size: $(du -sh ${BACKUP_DIR} | cut -f1)"

# ── 3. Reset state for fresh run ──
echo ""
echo "[3/5] Resetting state..."

# Reset self_model.json (BasalGanglia domain stats — all zeros)
cat > data/self_model.json << 'SELF_MODEL'
{}
SELF_MODEL
echo "  ✓ self_model.json → empty (BasalGanglia will populate from scratch)"

# Reset world_state.json (PrimordialLoop will rediscover)
cat > data/world_state.json << 'WORLD'
{"count": 0, "facts": []}
WORLD
echo "  ✓ world_state.json → empty (PrimordialLoop will rediscover)"

# Reset command_genome.json (BasalGanglia will evolve new genome)
cat > data/command_genome.json << 'GENOME'
{}
GENOME
echo "  ✓ command_genome.json → empty (genome evolves from tabula rasa seeds)"

# Reset knowledge_gaps.json (MetaCognition will rebuild)
cat > data/knowledge_gaps.json << 'GAPS'
{"domain_failure_counts": {}, "gaps": {}}
GAPS
echo "  ✓ knowledge_gaps.json → empty"

# Reset causal_graph.json
cat > data/causal_graph.json << 'CAUSAL'
{"nodes": {}, "edges": {}}
CAUSAL
echo "  ✓ causal_graph.json → empty"

# Reset concept hierarchy
cat > data/concept_hierarchy.json << 'HIER'
{"co_occurrence": {}, "composite_ops": {}, "sequence_counts": {}, "sequence_patterns": {}, "sequence_successes": {}, "total_completed_goals": 0}
HIER
echo "  ✓ concept_hierarchy.json → empty"

# Truncate metrics (fresh telemetry)
for f in data/metrics/*.jsonl; do
    [ -f "$f" ] && > "$f"
done
echo "  ✓ metrics/*.jsonl → truncated"

# Remove specialist caches (will be regenerated by neurogenesis)
rm -f data/specialist_*.json
echo "  ✓ specialist_*.json → removed"

# Keep operators.jsonl — bootstrap will regenerate, but this lets us compare
# Actually: truncate it too for a true fresh start
> data/operators.jsonl
echo "  ✓ operators.jsonl → truncated (bootstrap will repopulate)"

# Keep engrams — they're episodic memory, valuable for the hippocampus
echo "  ✓ engrams/ → kept (episodic memory preserved)"

# Keep self_model_primordial.json — it's the static identity, not learned state
echo "  ✓ self_model_primordial.json → kept (static identity)"

# ── 4. Recompile ──
echo ""
if [[ "${1:-}" != "--no-build" ]]; then
    echo "[4/5] Recompiling..."
    cmake --build build --parallel $(nproc) 2>&1 | tail -5
    echo "  ✓ Build complete"
else
    echo "[4/5] Skipping build (--no-build)"
fi

# ── 5. Verify ──
echo ""
echo "[5/5] Verification..."
echo "  State files:"
for f in self_model.json world_state.json command_genome.json knowledge_gaps.json operators.jsonl; do
    size=$(wc -c < "data/${f}" 2>/dev/null || echo "MISSING")
    echo "    ${f}: ${size} bytes"
done
echo "  Metrics:"
for f in data/metrics/*.jsonl; do
    lines=$(wc -l < "$f" 2>/dev/null || echo "MISSING")
    echo "    $(basename $f): ${lines} lines"
done

echo ""
echo "════════════════════════════════════════════════"
echo "  Ready for fresh run."
echo "  Backup at: ${BACKUP_DIR}"
echo ""
echo "  Start with:"
echo "    nohup ./build/cerebral_matrix > /dev/null 2>&1 &"
echo ""
echo "  Monitor with:"
echo "    tail -f data/metrics/intrinsic_goals.jsonl | python3 -c \\"
echo "      \"import sys,json"
echo "      for l in sys.stdin:"
echo "        j=json.loads(l)"
echo "        if j.get('event')=='intrinsic_goal_result':"
echo "          print(f'{j[\\\"domain\\\"]:20s} {\\\"✓\\\" if j[\\\"success\\\"] else \\\"✗\\\"} {j[\\\"command\\\"][:60]}')\""
echo "════════════════════════════════════════════════"
