#!/usr/bin/env python3
"""Generate ReflexLobe C++ source file — auto-generated lobe that monitors execution success rates."""
import os

CODE = r'''#include <zmq.hpp>
#include <nlohmann/json.hpp>
#include <common/routing.hpp>
#include <iostream>
#include <thread>
#include <chrono>

using json = nlohmann::json;

namespace neuroswarm {

// ReflexLobe — passive execution monitor.
//
// Auto-generated by NeuroSwarm cognitive system (NS-014).
// Listens to execution_result events and tracks success/failure rates.
// Biological analogue: cerebellar error monitoring circuit.

class ReflexLobe {
public:
    ReflexLobe(const std::string& ip = "localhost")
        : ctx(1), pub(ctx, zmq::socket_type::pub), sub(ctx, zmq::socket_type::sub) {
        pub.connect("tcp://" + ip + ":5555");
        sub.connect("tcp://" + ip + ":5556");
        routing::subscribe(sub, {"execution_result"});
        std::cout << "[REFLEX] Execution monitor online." << std::endl;
    }

    void start() {
        int total = 0, success = 0, failure = 0;
        while (true) {
            auto j = routing::receive(sub, zmq::recv_flags::dontwait);
            if (j.is_null()) {
                std::this_thread::sleep_for(std::chrono::milliseconds(100));
                continue;
            }
            if (j.value("intent", "") == "execution_result") {
                total++;
                if (j.value("status", "") == "success") success++;
                else failure++;

                if (total % 10 == 0) {
                    float rate = (total > 0) ? (float)success / total * 100.0f : 0.0f;
                    std::cout << "[REFLEX] " << success << "/" << total
                              << " (" << (int)rate << "% success rate)" << std::endl;
                }
            }
        }
    }

private:
    zmq::context_t ctx;
    zmq::socket_t pub;
    zmq::socket_t sub;
};

} // namespace neuroswarm

int main() {
    neuroswarm::ReflexLobe lobe;
    lobe.start();
    return 0;
}
'''

os.makedirs("src/lobes/ReflexLobe", exist_ok=True)
with open("src/lobes/ReflexLobe/ReflexLobe.cpp", "w") as f:
    f.write(CODE)

print(f"[GEN] Written {len(CODE)} bytes to src/lobes/ReflexLobe/ReflexLobe.cpp")
